CXX   = g++
 
# Change this to point at your Gecko SDK directory. 
GECKO_SDK_PATH = ../xulrunner-sdk
 
# GCC only define which allows us to not have to #include mozilla-config 
# in every .cpp file.  If your not using GCC remove this line and add 
# #include "mozilla-config.h" to each of your .cpp files. 
GECKO_CONFIG_INCLUDE = -include xpcom-config.h -fshort-wchar  

# use of -fshort-wchar is hack, for error in nsStringAPI.h 

NOTARY_COMMON = ../../common
NOTARY_CLIENT = ../../notary-client
 
GECKO_INCLUDES = -I $(GECKO_SDK_PATH)/include  -I $(GECKO_SDK_PATH)/sdk/include -I $(NOTARY_COMMON) -I $(NOTARY_CLIENT) 

 
GECKO_LDFLAGS =  -L$(GECKO_SDK_PATH)/lib -L$(GECKO_SDK_PATH)/bin -Wl,-rpath-link,$(GECKO_SDK_PATH)/bin -lxpcomglue_s -lxpcom -lnspr4 -lssl -lcrypto 

FILES = Perspectives.cpp PerspectivesModule.cpp $(NOTARY_COMMON)/notary_crypto.c $(NOTARY_CLIENT)/notary_local.c $(NOTARY_COMMON)/net_util.c $(NOTARY_COMMON)/notary_util.c contact_notary.c $(NOTARY_CLIENT)/client_policy.c $(NOTARY_COMMON)/flex_queue.c

TARGET = Perspectives.so

build:
	$(GECKO_SDK_PATH)/bin/xpidl -m header -I$(GECKO_SDK_PATH)/idl IPerspectives.idl 
	$(GECKO_SDK_PATH)/bin/xpidl -m typelib -I$(GECKO_SDK_PATH)/idl IPerspectives.idl 
	$(CXX) -Wall -Os -o $(TARGET) -lssl -lcrypto $(GECKO_CONFIG_INCLUDE) $(GECKO_DEFINES) $(GECKO_INCLUDES) -shared $(CXXFLAGS) $(FILES) $(GECKO_LDFLAGS) 
	chmod +x $(TARGET)
	strip $(TARGET)
 
clean: 
	rm $(TARGET)
