#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "cc -I../../common -O"
  #define PLATFORM "dist"
  #define DATE "Sat Jan  5 21:19:32 EST 2008"
#endif
