#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "cc -I../../common -O"
  #define PLATFORM "dist"
  #define DATE "Thu Jan 17 13:24:43 EST 2008"
#endif
