#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "cc -I../../common -O"
  #define PLATFORM "dist"
  #define DATE "Sun Jan  6 22:06:23 EST 2008"
#endif
